//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBrandInfoServiceClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarBrand", Namespace="http://schemas.datacontract.org/2004/07/CarInfoServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CarBrand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoundedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfEmployeesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoundedIn {
            get {
                return this.FoundedInField;
            }
            set {
                if ((this.FoundedInField.Equals(value) != true)) {
                    this.FoundedInField = value;
                    this.RaisePropertyChanged("FoundedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfEmployees {
            get {
                return this.NumberOfEmployeesField;
            }
            set {
                if ((this.NumberOfEmployeesField.Equals(value) != true)) {
                    this.NumberOfEmployeesField = value;
                    this.RaisePropertyChanged("NumberOfEmployees");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBrandInfoService")]
    public interface IBrandInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrandInfoService/GetInfo", ReplyAction="http://tempuri.org/IBrandInfoService/GetInfoResponse")]
        CarBrandInfoServiceClient.ServiceReference1.CarBrand GetInfo(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrandInfoService/GetInfo", ReplyAction="http://tempuri.org/IBrandInfoService/GetInfoResponse")]
        System.Threading.Tasks.Task<CarBrandInfoServiceClient.ServiceReference1.CarBrand> GetInfoAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrandInfoServiceChannel : CarBrandInfoServiceClient.ServiceReference1.IBrandInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrandInfoServiceClient : System.ServiceModel.ClientBase<CarBrandInfoServiceClient.ServiceReference1.IBrandInfoService>, CarBrandInfoServiceClient.ServiceReference1.IBrandInfoService {
        
        public BrandInfoServiceClient() {
        }
        
        public BrandInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrandInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrandInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrandInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarBrandInfoServiceClient.ServiceReference1.CarBrand GetInfo(string name) {
            return base.Channel.GetInfo(name);
        }
        
        public System.Threading.Tasks.Task<CarBrandInfoServiceClient.ServiceReference1.CarBrand> GetInfoAsync(string name) {
            return base.Channel.GetInfoAsync(name);
        }
    }
}
